apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - image: alklein/alklein_alation_app
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        imagePullPolicy: "IfNotPresent"
        name: app
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""

