apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
spec:
  replicas: 4
  selector:
    matchLabels:
      service: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - image: alklein/alation_app:1.4.0
        imagePullPolicy: "IfNotPresent"
        name: app
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        resources: {}
      restartPolicy: Always
