apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: proxy
  strategy: {}
  template:
    metadata:
      labels:
        service: proxy
    spec:
      containers:
      - image: alklein/alation_proxy
        imagePullPolicy: "IfNotPresent"
        name: proxy
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
